[package]
name = "title-search"
edition = "2021"
version = "0.1.0"

[dependencies]
tantivy = "0.19.0"
walkdir = "2.4"
regex = "1"
zstd = "0.13"

[[bin]]
name = "no-dependencies"
path = "no-dependencies/main.rs"

[[bin]]
name = "via-tantivy"
path = "via-tantivy/main.rs"
